# Site settings
title: folio
email: lorenz.walthert@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: lorenzwalthert
github_username:  lorenzwalthert
linkedin_username: lorenzwalthert

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
gems: [jekyll-paginate]
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


# include
include: ["_source", "tags"]
exclude: ["*.Rmd"] # exclude all rmd files.


